### ISSUE TITLE
Mekanism Digital Miner Wont Mine Silver

### ISSUE THREAD

**Issue by ILostMyleftNut** [Slurp-Space/Daves-Lab#5]
Digital miner wont mine silver in its filter from both oreDict oreSilver as well as using item stack to set its filter. Might happen with other ores, dont know as i havent tried.

**Comment by Raj4K** [comment]
When you put silver ore in the filter can you put it near the digital miner and see if the count goes up? If so, then there’s none in that area. If the number doesn’t increase scanning, then I’ll have to take a look.

**Comment by ILostMyleftNut** [comment]
> When you put silver ore in the filter can you put it near the digital miner and see if the count goes up? If so, then there’s none in that area. If the number doesn’t increase scanning, then I’ll have to take a look.

I put it right above a silver vein in the mining dimension, hit reset, cleared the config and re did it a few times.

**Comment by Raj4K** [comment]
> I put it right above a silver vein in the mining dimension, hit reset, cleared the config and re did it a few times.

When testing on single-player, I do not have this bug. Using the "oreSilver" oreDict.
![image](https://user-images.githubusercontent.com/76783527/103415043-79ec6580-4b4e-11eb-9f27-233b90a8ff25.png)

I will test on the server in a moment

**Comment by Raj4K** [comment]
Works on the server as well, likely a typo in the config key.
